/**
 * ミニ四駆自動運転 WebApp - 定数 & 設定
 */
export const UIState = {
    DISCONNECTED: 'DISCONNECTED',
    MANUAL: 'MANUAL',
    AUTO_PENDING: 'AUTO_PENDING',
    MANUAL_PENDING: 'MANUAL_PENDING',
    AUTO: 'AUTO',
    AUTO_TOR: 'AUTO_TOR',
    SAFE_STOP: 'SAFE_STOP',
    EMERGENCY_STOP: 'EMERGENCY_STOP'
};

export const MCUMode = {
    MANUAL: 'MANUAL',
    AUTO: 'AUTO',
    SAFE_STOP: 'SAFE_STOP',
    EMERGENCY_STOP: 'EMERGENCY_STOP'
};

export const ModeRequest = { NONE: 'NONE', MANUAL: 'MANUAL', AUTO: 'AUTO' };

export const StopReasonText = {
    OBSTACLE: 'OBSTACLE DETECTED',
    TOR_TIMEOUT: 'TOR TIMEOUT',
    EMERGENCY_BUTTON: 'EMERGENCY STOP',
    COMM_TIMEOUT: 'COMM TIMEOUT',
    SENSOR_ERROR: 'SENSOR ERROR'
};

export const RejectReasonText = {
    OBSTACLE_NEAR: 'OBSTACLE NEAR',
    SENSOR_NOT_READY: 'SENSOR NOT READY',
    IN_TOR: 'IN TOR WARNING',
    IN_EMERGENCY: 'IN EMERGENCY STOP',
    MODE_MISMATCH: 'MODE MISMATCH'
};

export const Config = {
    TRANSMIT_INTERVAL_MS: 100,
    WS_HEARTBEAT_TIMEOUT_MS: 1500,
    WS_RECONNECT_DELAY_MS: 1500,
    MODE_SWITCH_TIMEOUT_MS: 1000,
    ALERT_DISPLAY_DURATION_MS: 3000,
    DEFAULT_CAMERA_URL: '/video_feed',
    STORAGE_KEY_CAMERA_URL: 'mini4wd_camera_url',
    TOUCH_MAX_DISTANCE: 60,
    INPUT_DEADBAND: 0.05
};
