"""
Mini 4WD WebApp - プロトコルおよび制御定数定義
"""

class MCUMode:
    MANUAL = "MANUAL"
    AUTO = "AUTO"
    SAFE_STOP = "SAFE_STOP"
    EMERGENCY_STOP = "EMERGENCY_STOP"

class StopReason:
    NONE = "NONE"
    OBSTACLE = "OBSTACLE"
    TOR_TIMEOUT = "TOR_TIMEOUT"
    EMERGENCY_BUTTON = "EMERGENCY_BUTTON"
    COMM_TIMEOUT = "COMM_TIMEOUT"
    SENSOR_ERROR = "SENSOR_ERROR"

class RejectReason:
    NONE = "NONE"
    SENSOR_NOT_READY = "SENSOR_NOT_READY"
    OBSTACLE_NEAR = "OBSTACLE_NEAR"
    IN_TOR = "IN_TOR"
    IN_EMERGENCY = "IN_EMERGENCY"
    MODE_MISMATCH = "MODE_MISMATCH"

DEFAULT_PORT = 8765
DEFAULT_HOST = "0.0.0.0"
HEARTBEAT_INTERVAL_SEC = 0.1  # 100ms
DEADMAN_TIMEOUT_SEC = 0.3     # 300ms
